"""Preenche msgstr EN/ES para strings da Home (rodar após pybabel update)."""
from pathlib import Path

TRADUCOES = {
    "en": {
        "Agendamento online profissional": "Professional online booking",
        "Bem-vindo": "Welcome",
        "Agende com": "Book with",
        "Qualidade, praticidade e o portfólio do seu profissional em um só lugar.": "Quality, convenience, and your professional's portfolio in one place.",
        "Marcar Horário": "Book appointment",
        "Marcar horário": "Book appointment",
        "Acesso ao painel da equipe": "Team dashboard access",
        "Nossos catálogos": "Our catalogs",
        "Toque em um card para ver o portfólio de fotos": "Tap a card to view the photo portfolio",
        "fotos": "photos",
        "%(num)d foto": "%(num)d photo",
        "%(num)d fotos": "%(num)d photos",
        "Ver portfólio": "View portfolio",
        "Nenhuma foto neste catálogo ainda.": "No photos in this catalog yet.",
        "Fechar": "Close",
        "Logotipo de %(nome)s": "Logo of %(nome)s",
        "Ícone do estabelecimento": "Business icon",
        "Como deseja continuar?": "How would you like to continue?",
        "Abrir portfólio: %(titulo)s": "Open portfolio: %(titulo)s",
        "Galeria de fotos": "Photo gallery",
        "Foto %(num)d de %(total)d — %(titulo)s": "Photo %(num)d of %(total)d — %(titulo)s",
        "Foto anterior": "Previous photo",
        "Próxima foto": "Next photo",
        "Instagram": "Instagram",
        "Facebook": "Facebook",
        "WhatsApp": "WhatsApp",
        "© %(nome)s · %(marca)s": "© %(nome)s · %(marca)s",
        "AgendaSimples": "AgendaSimples",
        "Catálogo 1": "Catalog 1",
        "Catálogo 2": "Catalog 2",
        "Catálogo 3": "Catalog 3",
        "Catálogo 4": "Catalog 4",
        "Agende seu horário": "Book your appointment",
        "Reserve seu horário em poucos cliques": "Book your appointment in a few clicks",
        "Agendar": "Book now",
        "Redes sociais": "Social media",
        "Siga-nos e fique por dentro das novidades": "Follow us for news and updates",
        "Nome completo": "Full name",
        "Digite seu nome completo": "Enter your full name",
        "Ex.: +55 19 99999-9999": "E.g. +1 555 123-4567",
        "Selecione o profissional": "Select a professional",
        "Escolha um profissional": "Choose a professional",
        "Profissional sugerido pelo seu link de agendamento.": "Professional suggested by your booking link.",
        "Data desejada": "Preferred date",
        "Escolha o horário": "Choose a time",
        "Selecione um horário": "Select a time slot",
        "Selecione o serviço": "Select a service",
        "Corte": "Haircut",
        "Corte e Barba": "Haircut and beard",
        "Corte + Sobrancelha": "Haircut + eyebrows",
        "Barba": "Beard",
        "Outro": "Other",
        "Confirmar agendamento": "Confirm booking",
        "Voltar para a página inicial": "Back to home page",
        "Marcar Horário": "Book appointment",
        "Login": "Login",
        "Login do Profissional": "Professional login",
        "E-mail": "Email",
        "Digite seu e-mail": "Enter your email",
        "Senha": "Password",
        "Digite sua senha": "Enter your password",
        "Entrar": "Sign in",
        "Esqueci minha senha": "Forgot my password",
        "Login - Barber Agenda": "Login - Barber Agenda",
        "Ações destrutivas": "Destructive actions",
        "Excluir Fichário": "Delete Binder",
        "Excluir Foto": "Delete Photo",
        "Use com cuidado: a exclusão é permanente.": "Use with care: deletion is permanent.",
        "Tem certeza que deseja excluir o fichário?": "Are you sure you want to delete the binder?",
        "Tem certeza que deseja excluir a foto?": "Are you sure you want to delete the photo?",
        "Criar conta": "Create account",
        "Comece grátis": "Start for free",
        "%(days)s dias de teste — sem cartão de crédito": "%(days)s-day trial — no credit card",
        "Nome do negócio": "Business name",
        "Ex.: Studio Bella, Clínica Horizonte": "E.g. Studio Bella, Horizon Clinic",
        "Seu nome (profissional)": "Your name (professional)",
        "Ex.: Maria Silva": "E.g. Maria Silva",
        "seu@email.com": "you@email.com",
        "Mínimo 6 caracteres": "At least 6 characters",
        "Confirmar senha": "Confirm password",
        "Repita a senha": "Repeat password",
        "Criar minha conta": "Create my account",
        "Já tem conta?": "Already have an account?",
        "Criar conta grátis": "Create free account",
        "Informe o nome do seu negócio.": "Enter your business name.",
        "Informe o seu nome.": "Enter your name.",
        "Informe um e-mail válido.": "Enter a valid email.",
        "A senha deve ter pelo menos 6 caracteres.": "Password must be at least 6 characters.",
        "As senhas não coincidem.": "Passwords do not match.",
        "Este e-mail já está cadastrado. Faça login ou use outro e-mail.": "This email is already registered. Sign in or use another email.",
        "Já existe uma conta com este e-mail ou nome de negócio semelhante.": "An account with this email or similar business name already exists.",
        "Bem-vindo! Sua conta foi criada com %(days)s dias de teste grátis.": "Welcome! Your account was created with a %(days)s-day free trial.",
        "Não foi possível criar sua conta. Tente novamente em instantes.": "Could not create your account. Please try again shortly.",
        "Conta criada, mas falhou o login automático. Entre com seu e-mail.": "Account created, but auto sign-in failed. Please sign in with your email.",
    },
    "es": {
        "Agendamento online profissional": "Reserva online profesional",
        "Bem-vindo": "Bienvenido",
        "Agende com": "Reserve con",
        "Qualidade, praticidade e o portfólio do seu profissional em um só lugar.": "Calidad, practicidad y el portafolio de su profesional en un solo lugar.",
        "Marcar Horário": "Reservar horario",
        "Marcar horário": "Reservar horario",
        "Acesso ao painel da equipe": "Acceso al panel del equipo",
        "Nossos catálogos": "Nuestros catálogos",
        "Toque em um card para ver o portfólio de fotos": "Toque una tarjeta para ver el portafolio de fotos",
        "fotos": "fotos",
        "%(num)d foto": "%(num)d foto",
        "%(num)d fotos": "%(num)d fotos",
        "Ver portfólio": "Ver portafolio",
        "Nenhuma foto neste catálogo ainda.": "Aún no hay fotos en este catálogo.",
        "Fechar": "Cerrar",
        "Logotipo de %(nome)s": "Logotipo de %(nome)s",
        "Ícone do estabelecimento": "Ícono del establecimiento",
        "Como deseja continuar?": "¿Cómo desea continuar?",
        "Abrir portfólio: %(titulo)s": "Abrir portafolio: %(titulo)s",
        "Galeria de fotos": "Galería de fotos",
        "Foto %(num)d de %(total)d — %(titulo)s": "Foto %(num)d de %(total)d — %(titulo)s",
        "Foto anterior": "Foto anterior",
        "Próxima foto": "Foto siguiente",
        "Instagram": "Instagram",
        "Facebook": "Facebook",
        "WhatsApp": "WhatsApp",
        "© %(nome)s · %(marca)s": "© %(nome)s · %(marca)s",
        "AgendaSimples": "AgendaSimples",
        "Catálogo 1": "Catálogo 1",
        "Catálogo 2": "Catálogo 2",
        "Catálogo 3": "Catálogo 3",
        "Catálogo 4": "Catálogo 4",
        "Agende seu horário": "Reserve su horario",
        "Reserve seu horário em poucos cliques": "Reserve su horario en pocos clics",
        "Agendar": "Reservar",
        "Redes sociais": "Redes sociales",
        "Siga-nos e fique por dentro das novidades": "Síganos y manténgase al día",
        "Nome completo": "Nombre completo",
        "Digite seu nome completo": "Escriba su nombre completo",
        "Ex.: +55 19 99999-9999": "Ej.: +55 19 99999-9999",
        "Selecione o profissional": "Seleccione el profesional",
        "Escolha um profissional": "Elija un profesional",
        "Profissional sugerido pelo seu link de agendamento.": "Profesional sugerido por su enlace de reserva.",
        "Data desejada": "Fecha deseada",
        "Escolha o horário": "Elija el horario",
        "Selecione um horário": "Seleccione un horario",
        "Selecione o serviço": "Seleccione el servicio",
        "Corte": "Corte",
        "Corte e Barba": "Corte y barba",
        "Corte + Sobrancelha": "Corte + cejas",
        "Barba": "Barba",
        "Outro": "Otro",
        "Confirmar agendamento": "Confirmar reserva",
        "Voltar para a página inicial": "Volver a la página inicial",
        "Marcar Horário": "Reservar horario",
        "Login": "Iniciar sesión",
        "Login do Profissional": "Acceso del profesional",
        "E-mail": "Correo electrónico",
        "Digite seu e-mail": "Escriba su correo",
        "Senha": "Contraseña",
        "Digite sua senha": "Escriba su contraseña",
        "Entrar": "Entrar",
        "Esqueci minha senha": "Olvidé mi contraseña",
        "Login - Barber Agenda": "Inicio de sesión - Barber Agenda",
        "Ações destrutivas": "Acciones destructivas",
        "Excluir Fichário": "Eliminar portafolio",
        "Excluir Foto": "Eliminar foto",
        "Use com cuidado: a exclusão é permanente.": "Úselo con cuidado: la eliminación es permanente.",
        "Tem certeza que deseja excluir o fichário?": "¿Está seguro de que desea eliminar el portafolio?",
        "Tem certeza que deseja excluir a foto?": "¿Está seguro de que desea eliminar la foto?",
        "Criar conta": "Crear cuenta",
        "Comece grátis": "Empiece gratis",
        "%(days)s dias de teste — sem cartão de crédito": "%(days)s días de prueba — sin tarjeta",
        "Nome do negócio": "Nombre del negocio",
        "Ex.: Studio Bella, Clínica Horizonte": "Ej.: Studio Bella, Clínica Horizonte",
        "Seu nome (profissional)": "Su nombre (profesional)",
        "Ex.: Maria Silva": "Ej.: María Silva",
        "seu@email.com": "su@email.com",
        "Mínimo 6 caracteres": "Mínimo 6 caracteres",
        "Confirmar senha": "Confirmar contraseña",
        "Repita a senha": "Repita la contraseña",
        "Criar minha conta": "Crear mi cuenta",
        "Já tem conta?": "¿Ya tiene cuenta?",
        "Criar conta grátis": "Crear cuenta gratis",
        "Informe o nome do seu negócio.": "Indique el nombre de su negocio.",
        "Informe o seu nome.": "Indique su nombre.",
        "Informe um e-mail válido.": "Indique un correo válido.",
        "A senha deve ter pelo menos 6 caracteres.": "La contraseña debe tener al menos 6 caracteres.",
        "As senhas não coincidem.": "Las contraseñas no coinciden.",
        "Este e-mail já está cadastrado. Faça login ou use outro e-mail.": "Este correo ya está registrado. Inicie sesión u use otro correo.",
        "Já existe uma conta com este e-mail ou nome de negócio semelhante.": "Ya existe una cuenta con este correo o nombre de negocio similar.",
        "Bem-vindo! Sua conta foi criada com %(days)s dias de teste grátis.": "¡Bienvenido! Su cuenta fue creada con %(days)s días de prueba gratis.",
        "Não foi possível criar sua conta. Tente novamente em instantes.": "No fue posible crear su cuenta. Intente de nuevo en un momento.",
        "Conta criada, mas falhou o login automático. Entre com seu e-mail.": "Cuenta creada, pero falló el inicio automático. Entre con su correo.",
    },
}


def aplicar(po_path: Path, lang: str):
    texto = po_path.read_text(encoding="utf-8")
    for msgid, msgstr in TRADUCOES[lang].items():
        bloco_vazio = f'msgid "{msgid}"\nmsgstr ""'
        bloco_ok = f'msgid "{msgid}"\nmsgstr "{msgstr}"'
        if bloco_vazio in texto:
            texto = texto.replace(bloco_vazio, bloco_ok, 1)
        elif f'msgid "{msgid}"' in texto and f'msgstr "{msgstr}"' not in texto:
            import re
            texto = re.sub(
                rf'msgid "{re.escape(msgid)}"\n(?:#, fuzzy\n)?msgstr "[^"]*"',
                bloco_ok,
                texto,
                count=1,
            )
    po_path.write_text(texto, encoding="utf-8")
    print(f"OK — {po_path}")


def main():
    base = Path(__file__).parent / "translations"
    aplicar(base / "en" / "LC_MESSAGES" / "messages.po", "en")
    aplicar(base / "es" / "LC_MESSAGES" / "messages.po", "es")


if __name__ == "__main__":
    main()
